#############################################################################
# Generated by PAGE version 4.12
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra39
    set site_4_0 $site_3_0.scr42
    set site_3_0 $base.fra46
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 924x606+561+179
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 573 \
        -width 717 
    vTcl:DefineAlias "$top.fra39" "mainFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra39
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr42 \
        -background {#d9d9d9} -height 539 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 721 
    vTcl:DefineAlias "$site_3_0.scr42" "displayLST" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr42.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    button $site_3_0.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but43" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but44" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but45" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but55" "Button5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.scr42 \
        -in $site_3_0 -x 2 -y 2 -width 0 -relwidth 0.99 -height 0 \
        -relheight 0.92 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 10 -y 580 -width 126 -relwidth 0 -height 33 \
        -relheight 0 -anchor sw -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 200 -y 580 -width 136 -relwidth 0 -height 33 \
        -relheight 0 -anchor sw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 710 -y 580 -width 156 -relwidth 0 -height 33 \
        -relheight 0 -anchor se -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 140 -y 580 -anchor sw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 575 \
        -width 165 
    vTcl:DefineAlias "$top.fra46" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    button $site_3_0.but47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but47" "Button4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che48 
    vTcl:DefineAlias "$site_3_0.che48" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che49 
    vTcl:DefineAlias "$site_3_0.che49" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che50 
    vTcl:DefineAlias "$site_3_0.che50" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che51 
    vTcl:DefineAlias "$site_3_0.che51" "Checkbutton4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che52 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che52 
    vTcl:DefineAlias "$site_3_0.che52" "Checkbutton5" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che53 
    vTcl:DefineAlias "$site_3_0.che53" "Checkbutton6" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che54 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che54 
    vTcl:DefineAlias "$site_3_0.che54" "Checkbutton7" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Check -variable che56 
    vTcl:DefineAlias "$site_3_0.che56" "Checkbutton8" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 160 -y 580 -width 155 -relwidth 0 -height 33 \
        -relheight 0 -anchor se -bordermode ignore 
    place $site_3_0.che48 \
        -in $site_3_0 -x 10 -y 10 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che49 \
        -in $site_3_0 -x 10 -y 40 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che50 \
        -in $site_3_0 -x 10 -y 70 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che51 \
        -in $site_3_0 -x 10 -y 100 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che52 \
        -in $site_3_0 -x 10 -y 130 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che53 \
        -in $site_3_0 -x 10 -y 160 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che54 \
        -in $site_3_0 -x 10 -y 190 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che56 \
        -in $site_3_0 -x 10 -y 510 -width 148 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra39 \
        -in $top -x 10 -y 10 -width 0 -relwidth 0.78 -height 0 \
        -relheight 0.97 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.985 -y 10 -width 165 -relwidth 0 -height 0 \
        -relheight 0.97 -anchor ne -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

