#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 17, 2018 11:32:43 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global che48
    che48 = StringVar()
    global che49
    che49 = StringVar()
    global che50
    che50 = StringVar()
    global che51
    che51 = StringVar()
    global che52
    che52 = StringVar()
    global che53
    che53 = StringVar()
    global che54
    che54 = StringVar()
    global che56
    che56 = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import arrowVerseTracker
    arrowVerseTracker.vp_start_gui()


